name: Affected Projects CI

on:
  push:
    branches: 
      - '**'  # Trigger on pushes to any branch
  pull_request:
    branches: 
      - main  # Trigger on PRs targeting the `main` branch

jobs:
  get-affected:
    runs-on: ubuntu-latest
    outputs:
      affected-projects: ${{ steps.set-matrix.outputs.affected-projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Fetch base branch (main)
        run: |
          git fetch origin main --depth=1

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get affected projects
        id: set-matrix
        run: |
          echo "affected-projects=$(npx nx show projects --affected --base=origin/main --head=HEAD --json)" >> $GITHUB_OUTPUT

  build:
    needs: get-affected
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.get-affected.outputs.affected-projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is cloned

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build affected project ${{ matrix.project }}
        run: pnpm nx build ${{ matrix.project }}

      - name: Test affected project ${{ matrix.project }}
        run: pnpm nx test ${{ matrix.project }}
